site_name: Codebase Architecture
site_url: https://mcklay.github.io/codebase-architecture/
site_author: Clay Mark Sarte
site_description: A Practical Guide to Structuring React + FastAPI Projects in the Age of AI

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  hide:
    - toc

nav:
  - Table of Contents: index.md

  - "":
      - "&nbsp; Preface": Preface.md
      - "&nbsp;&nbsp; 📖 Part I: Foundations": PartI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 1": chapter1.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 2": chapter2.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 3": chapter3.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 4": chapter4.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 5": chapter5.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 6": chapter6.md

      - "&nbsp;&nbsp; 📖 Part II: Modularity": PartII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 7": chapter7.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 8": chapter8.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 9": chapter9.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 10": chapter10.md

      - "&nbsp;&nbsp; 📖 Part III: Scalability": PartIII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 11": chapter11.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 12": chapter12.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 13": chapter13.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 14": chapter14.md

      - "&nbsp;&nbsp; 📖 Part IV: Hybrid and Advanced Techniques": PartIV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 15": chapter15.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 16": chapter16.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 17": chapter17.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 18": chapter18.md

      - "&nbsp;&nbsp; 📖 Part V: Case Studies and Templates": PartV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 19": chapter19.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 20": chapter20.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 21": chapter21.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 22": chapter22.md

      - "&nbsp;&nbsp; 📖 Appendices": appendices.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McKlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/clay-mark-sarte-283855147/
